language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install: gem install bundler -v 1.16.2
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/4.2.gemfile
