name: ci
on: [pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - ruby-head
        rails_version:
          - "7.0"
          - "6.1"
          - "6.0"
          - "5.2"
        exclude:
          - ruby: "2.6"
            rails_version: "7.0"
          - ruby: "3.0"
            rails_version: "5.2"
          - ruby: "3.1"
            rails_version: "5.2"
          - ruby: "3.1"
            rails_version: "6.0"
          - ruby: ruby-head
            rails_version: "5.2"
          - ruby: ruby-head
            rails_version: "6.0"
          - ruby: ruby-head
            rails_version: "6.1"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails_version }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
